---
- hosts: web_servers
  become: true
  tasks:
    - name: Print OS info
      ansible.builtin.package:
        name: apache2

    - name: start apache
      service:
        name: apache2
        state: started
        enabled: yes  
